// Raw palette / legacy token classes each file may still use while the views
// migrate to the semantic tokens (see rawclasses.ts). A ratchet: counts only go
// down — rawclasses.test.ts fails on a new raw class, and asks to lower the
// number here when a file improves. The migration is done when this is empty.
export const RAW_CLASS_BASELINE: Readonly<Record<string, number>> = {
  '../App.tsx': 17,
  '../components/Accounts.tsx': 7,
  '../components/BackupControl.tsx': 5,
  '../components/CardStatements.tsx': 27,
  '../components/CardsView.tsx': 6,
  '../components/CategoriesView.tsx': 8,
  '../components/CsvImport.tsx': 9,
  '../components/CuotaDialog.tsx': 4,
  '../components/DuesBanner.tsx': 8,
  '../components/ErrorBoundary.tsx': 5,
  '../components/ExpenseForm.tsx': 17,
  '../components/FixedExpensesView.tsx': 12,
  '../components/ForecastView.tsx': 28,
  '../components/ImportInboxView.tsx': 45,
  '../components/IncomePanel.tsx': 11,
  '../components/MailSettings.tsx': 11,
  '../components/MerchantsView.tsx': 5,
  '../components/MonthView.tsx': 64,
  '../components/Receivables.tsx': 8,
  '../components/ReconcileDialog.tsx': 7,
  '../components/RecurringSuggestions.tsx': 5,
  '../components/RefundDialog.tsx': 1,
  '../components/RestoreBackup.tsx': 16,
  '../components/SavingsView.tsx': 19,
  '../components/SearchView.tsx': 13,
  '../components/SettingsView.tsx': 17,
  '../components/StatementImport.tsx': 9,
  '../components/SyncNoticeBox.tsx': 9,
  '../components/TagsSection.tsx': 5,
  '../components/TrashView.tsx': 12,
  '../components/TrendPanel.tsx': 11,
  '../components/UpdateNotice.tsx': 13,
  '../components/UserSwitcher.tsx': 26,
  '../components/WebBackup.tsx': 17,
  '../components/WebUpdateBanner.tsx': 2,
  '../components/YearView.tsx': 22,
  '../main.tsx': 5,
}
