// Web-build stand-in for '@/services/finance' (aliased by vite --mode web):
// same call surface as the Wails bindings wrapper, backed by the local SQLite
// engine running in the worker instead of the Go backend.
import { remoteService } from '@/services/web/worker-client'
import type { FinanceServiceContract } from '@/services/contract'

export const FinanceService = remoteService<FinanceServiceContract>('finance')

export type {
  Account,
  AccountView,
  AccountsClosing,
  AccountsSummary,
  BaseSalary,
  BudgetStatus,
  Card,
  CardDebt,
  CardOwed,
  CardResult,
  CardStatement,
  CardStatementDetail,
  CardStatementDetailResult,
  CardStatementImport,
  CardStatementImportResult,
  CardStatementInput,
  CardStatementLine,
  CardStatementLineInput,
  CardStatementLineView,
  CardStatementScheduleEntry,
  CardStatementView,
  CardStatementsResult,
  Category,
  CategoryBudgetView,
  CategoryBudgetsResult,
  CategoryResult,
  CategoryTotal,
  CategoryYearRow,
  Due,
  DuesResult,
  Expense,
  ExpenseFilter,
  ExpenseHit,
  ExpenseResult,
  ExpenseSearch,
  ExpenseSearchResult,
  ForecastMonth,
  ForecastResult,
  FixedExpense,
  FixedExpenseResult,
  FixedExpenseView,
  ImportBatch,
  ImportCandidate,
  ImportItem,
  ImportItemView,
  ImportItemsResult,
  Income,
  IncomeResult,
  Merchant,
  MerchantResult,
  MerchantRule,
  MonthlySummary,
  MonthlySummaryResult,
  Movimiento,
  OpResult,
  PeriodSalary,
  Reconciliation,
  ReconciliationResult,
  ReconciliationStatus,
  RecurringSuggestion,
  Refund,
  RefundResult,
  Tag,
  TagView,
  SalaryResult,
  SavingsContribution,
  SavingsGoal,
  SavingsGoalView,
  Settings,
  SettingsResult,
  SpendingTrend,
  StageResult,
  StageSummary,
  Transfer,
  TransferResult,
  CatalogSummary,
  CatalogResult,
  TrashItem,
  TrashResult,
  TrendMonth,
  YearMonth,
  YearSummary,
  YearSummaryResult,
} from '@/services/contract'

export const KIND_UNICO = 'unico'
export const KIND_CUOTAS = 'cuotas'
export const STATUS_PENDIENTE = 'pendiente'
export const STATUS_PAGADO = 'pagado'
export const SOURCE_CUOTA = 'cuota'
export const SOURCE_FIJO = 'fijo'
export const SOURCE_REEMBOLSO = 'reembolso'
