import { describe, expect, it } from 'vitest'
import raw from '@/lib/statements/itau/testdata/account-statement.runs.json?raw'
import { groupRows, rowText, type TextRun } from '@/lib/statements/layout'
import { isClAmount, parseClAmount, parseClDate } from '@/lib/statements/amounts'
import { hintFor } from '@/lib/statements/itau/accountStatement'
import { parseStatement } from '@/lib/statements/detect'
import { StatementFormatError } from '@/lib/statements/types'

// Anonymized runs of a real Itaú cartola (names, account/operation numbers
// replaced; amounts doubled so the daily balances still add up). Pages: USD
// account, CLP account with 15 movements, line of credit.
// JSON.parse returns unknown data; the fixture is generated by
// scripts/pdf-runs.mjs, whose output has exactly the TextRun shape.
const fixture = JSON.parse(raw) as TextRun[]

describe('montos y fechas chilenos', () => {
  it.each([
    ['1.086.319', '1086319'],
    ['80.000', '80000'],
    ['0', '0'],
    ['1.234,50', '1234.50'],
    ['1086.319', null],
    ['12.00', null],
  ])('%s → %s', (input, want) => {
    expect(parseClAmount(input)).toBe(want)
    expect(isClAmount(input)).toBe(want !== null)
  })

  it('fechas dd/mm/aaaa', () => {
    expect(parseClDate('31/07/2026')).toBe('2026-07-31')
    expect(parseClDate('2026-07-31')).toBeNull()
  })
})

describe('groupRows', () => {
  it('agrupa por línea base con tolerancia y ordena de arriba abajo e izquierda a derecha', () => {
    const run = (str: string, x: number, y: number, page = 1): TextRun => ({ page, str, x, y, width: 10 })
    const rows = groupRows([run('b', 50, 100.9), run('a', 10, 100), run('c', 10, 90), run(' ', 0, 90), run('d', 0, 200, 2)])
    expect(rows.map(rowText)).toEqual(['a b', 'c', 'd'])
  })
})

describe('cartola Itaú', () => {
  it('lee los cargos de la cuenta en pesos, reconstruyendo filas por coordenadas', () => {
    const parsed = parseStatement(fixture)
    expect(parsed.format).toBe('Cartola Itaú (cuenta corriente)')
    expect(parsed.warnings).toEqual([])
    expect(parsed.batch.source).toBe('pdf_account')
    expect(parsed.batch.issuer).toBe('itau')

    const items = parsed.batch.items
    expect(items.map((it) => [it.date, it.description, it.amount, it.reference, it.hint])).toEqual([
      ['2026-07-08', 'TRANSFERENCIA A JUAN SOTO', '160000', '100000003', 'transfer'],
      ['2026-07-17', 'CRUZ VERDE L9093 CHILLAN C', '32364', '', ''],
      ['2026-07-24', 'COBRO NOTARIO LP', '4000', '', ''],
      ['2026-07-29', 'TRANSFERENCIA A PEDRO ROJAS', '300000', '100000005', 'transfer'],
      ['2026-07-29', 'TRANSFERENCIA A CMR MC BJ', '24000', '100000006', 'card_payment'],
      ['2026-07-31', 'TRANSFERENCIA A MARIA GONZALEZ', '400000', '100000008', 'transfer'],
      ['2026-07-31', 'PAGO DEUDA INTER. TC CTA CLP', '274300', '', 'card_payment'],
      ['2026-07-31', 'ENTEL PCS PAGO ENSANTIAGO C', '33980', '', ''],
      ['2026-07-31', 'TRANSFERENCIA A LAURA MUNOZ', '2172638', '100000010', 'transfer'],
      ['2026-07-31', 'TRANSFERENCIA A SERVIPAG LTDA', '76576', '100000011', 'transfer'],
    ])
    for (const it of items) expect(it).toMatchObject({ account: '0222222255', currency: 'CLP', installmentsTotal: 1 })

    expect(parsed.notes).toEqual([
      'Cuenta 1111111110 en DOLAR: se omite (sólo se importan cuentas en pesos).',
      'Cuenta 0222222255 (pesos) 01/07/2026 - 31/07/2026: 10 cargos leídos, 5 abonos no se importan.',
      'Línea de crédito 0222222265: se omite (sus giros financian la cuenta, no son gastos).',
    ])
  })

  it('no depende del orden en que el PDF entrega el texto', () => {
    const reversed = parseStatement(fixture.toReversed())
    expect(reversed.batch.items).toEqual(parseStatement(fixture).batch.items)
  })

  it('avisa cuando los saldos diarios no cuadran (una fila mal leída)', () => {
    // Drop the Cruz Verde charge: the next reported balance no longer adds up.
    const tampered = fixture.filter((r) => !(r.page === 2 && r.str === '32.364'))
    const parsed = parseStatement(tampered)
    expect(parsed.warnings).toEqual([
      'Cuenta 0222222255: el saldo del 2026-07-17 no cuadra (calculado 818210, informado 785846). Revisa los movimientos importados.',
      'Cuenta 0222222255: la fila del 2026-07-17 «CRUZ VERDE L9093 CHILLAN C» no tiene monto legible.',
    ])
  })

  it('rechaza una cartola sin las columnas esperadas', () => {
    const noCargos = fixture.filter((r) => r.str !== 'Cargos')
    expect(() => parseStatement(noCargos)).toThrow(StatementFormatError)
    expect(() => parseStatement(noCargos)).toThrow(/faltan columnas.*cargo/)
  })

  it('rechaza documentos de formato desconocido', () => {
    const other: TextRun[] = [{ page: 1, str: 'ESTADO DE CUENTA TARJETA DE CRÉDITO', x: 0, y: 0, width: 10 }]
    expect(() => parseStatement(other)).toThrow(/No se reconoce el formato/)
  })
})

describe('pistas de doble conteo', () => {
  it.each([
    ['PAGO DEUDA INTER. TC CTA CLP', 'card_payment'],
    ['PAGO TARJETA CREDITO', 'card_payment'],
    ['TRANSFERENCIA A CMR MC BJ', 'card_payment'],
    ['TRANSFERENCIA A JUAN SOTO', 'transfer'],
    ['TRANSFERENCIA DE ANA PEREZ', ''],
    ['CRUZ VERDE L9093 CHILLAN C', ''],
  ])('%s → %s', (description, hint) => {
    expect(hintFor(description)).toBe(hint)
  })
})
